mini_insta/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from . import views
from django.conf import settings


app_name = 'accounts'

urlpatterns = [
    path('login1/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login_view, name="login"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name="profile"),
    path('update/<int:pk>/', views.ProfileUpdateView.as_view(), name='update'),
    path('email_change/', views.emial_change, name='email_change'),
    path('new_emial_activate/<uidb64>/<token>/', views.new_email_activate, name='new_email_activate'),


    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html", 
        email_template_name='accounts/password_reset_email.html',
        success_url='/accounts/reset_password_sent/'),
        name='reset_password'),

    path('reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_done.html",
        success_url='/accounts/reset_password_complete/'),
        name='password_reset_confirm'),

    path('reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_succes"),
        name='password_reset_complete'),

] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mini_insta/mini_insta/urls.py
from django.contrib import admin
from django.urls import path, include
from my_site import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(), name="home"),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('groups/', include('groups.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mini_insta/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns= [
    path('create/', views.create_post, name='create_post'),
    path('list/', views.PostListView.as_view(), name='list'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', views.detail_view, name='detail'),


]

mini_insta/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
import datetime
from django.urls import reverse
# Create your models here.

User = get_user_model()

class Post(models.Model):
    author = models.ForeignKey(User, related_name='author', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='posts_image')
    caption = models.TextField(blank=True, null=True)
    date_of_publication = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['date_of_publication']

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f'Author of post {self.author}'

class Like(models.Model):
    post = models.ForeignKey(Post, related_name='like', on_delete=models.CASCADE)
    like_author = models.OneToOneField(User, related_name='like_author', on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    comment_author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    date_of_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['date_of_created']

    def __str__(self):
        return f'Comment {self.body} by {self.comment_author}'

mini_insta/posts/forms.py
from django.forms import ModelForm
from .models import Comment

#POST FORMS.PY

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

mini_insta/posts/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponseForbidden, Http404
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, TemplateView
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import FormMixin

from .forms import CommentForm
from .models import Post, Like

def detail_view(request, pk):
    post = Post.objects.get(pk=pk)
    image = post.image
    caption = post.caption
    author = post.author
    date = post.date_of_publication

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if 'create_comment' in request.POST:

            if comment_form.is_valid():
                comment_form = comment_form.save(commit=False)
                comment_form.comment_author = request.user
                comment_form.post = post
                comment_form.body = request.POST.get('body')
                comment_form.save()
                return redirect('posts:detail', pk=pk)
        elif 'like' in request.POST:
            try:
                if Like.objects.get(post=post, like_author=request.user) in Like.objects.all():
                    Like.objects.get(post=post, like_author=request.user).delete()
                    user_like = 'like'
                    return redirect('posts:detail', pk=pk)
                else:
                    Like.objects.create(like_author=request.user, post=post)
                    user_like = 'dislike'
                    return redirect('posts:detail', pk=pk)                                        
            except:
                Like.objects.create(like_author=request.user, post=post)
                user_like = 'dislike'
                return redirect('posts:detail', pk=pk)       

    else:
        comment_form = CommentForm()


    context = {
        'post':post, 'image':image, 'caption':caption, 'author':request.user, 'date':date,
    }

    return render(request,  'posts/detail.html',context)



@login_required 
def create_post(request):
    if request.POST:
        if 'create_post' in request.POST:
            caption = request.POST.get('caption')
            image = request.FILES.get('image')
            user = request.user

            Post.objects.create(author=user, caption=caption, image=image)

            return redirect('posts:list')

    context = {

  }
    return render(request, 'posts/create_post.html', context)


class PostListView(ListView):

    model = Post
    reverse_lazy('about')




class PostDeleteView(DeleteView):

    model = Post
    template_name = 'posts/confirm_delete.html'

    success_url = reverse_lazy('posts:list')



    def get_queryset(self):
        user = self.request.user
        return Post.objects.get(author=user)



class PostUpdateView(UpdateView):

    model = Post

    fields = ['image', 'caption']

    success_message = "Updated Successfully" 

    success_url = reverse_lazy('posts:list')

mini_insta/posts/templates/posts/confirm_delete.html
{% extends 'base.html' %}
{% block conntent %}
<h4>Are you sure you wont delete this post?</h4>

<div class="card text-center" style="width: 30rem;">
    <form method="POST">
        {% csrf_token %}
        <div class="container">

            <img src="{{object.image.url}}" class="card-img-top" alt="Card image cap">
            <p class="card-text">{{ object.caption }}</p>
            <input type="submit" class="btn btn-danger container" value="delete">
        </div>

    </form>
</div>



{% endblock %}

mini_insta/posts/templates/posts/create_post.html
{% extends 'base.html' %}
{% block conntent %}

    <form method='POST' enctype='multipart/form-data'>
        {% csrf_token %}
        <br/>
        <div class="form-group">
            <label for="id_image"><strong>Chose image to publicate:</strong></label>
            <input type="file" class="form-control-file" accept='image/*' id="id_image" required name="image">   
        </div>
        <div class="form-group">
            <label for="id_caption">Your caption to image</label>
            <textarea class="form-control" id="id_caption" rows="3" name="caption"></textarea>
        </div>

        <input type="submit" class="btn btn-primary" value="add post" name="create_post">
    </form>

{% endblock %}

mini_insta/posts/templates/posts/detail.html
{% extends 'base.html' %}
{% block conntent %}


<div class="container jumbotron">
    <h1>{{like}}</h1>
    <img src="{{ image.url }}" alt="">
    <p>{{ caption }}</p>

    <form method="POST">
        {% csrf_token %}
        Likes: {{ post.like.all.count }}
        <input type="submit" value="{{ like }}" class=" btn btn-primary" name="like">
    </form>


    <h4>Comments for this photo:</h4>
    {% for comment in post.comments.all %}
        <li class="list-group-item">
            <p>Comment by:<strong>{{ comment.comment_author }}</strong></p>
            <p><strong>Comment: </strong> {{ comment.body }}</p>
        </li>
    {% empty %}
        <li>
            <p>No comments</p>
        </li>     
    {% endfor %}
    </ul>

    <form method="POST">
        {% csrf_token %}
        <!-- {{ comment_form.as_p }} -->
        <label for="id_body">Add new comment</label>
        <textarea class="form-control" name="body" id="id_body" cols="30" rows="5"></textarea>
        <input type="submit" value="add" class="btn btn-primary" name="create_comment">
    </form>

</div>





{% endblock %}

mini_insta/posts/templates/posts/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="add" name="create_comment">
    </form>
</body>
</html>

mini_insta/posts/templates/posts/img.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <img src="/home/dominika/folders/projects/website/mini_insta/media/posts_image/download_3_SPtpDcI.jpeg" alt="">
</body>
</html>

mini_insta/posts/templates/posts/list_view.html
{% extends 'base.html' %}
{% block conntent %}

{% if not posts %}
    <h3>No posts</h3>
    
{% else %}
    {% for post in posts %}
        <img src="{{post.image}}">
        <a href="{% url 'posts:detail' post.pk %}">detail</a>
        <a href="{% url 'posts:update' post.pk %}">update</a>
        <h1>asdfaff</h1>
        {{ post.image }}
        {{ post.caption }}
        {{ post.author }}
        {{ post.date_of_creation }}
        
    {% endfor %}
{% endif%}



{% endblock %}

mini_insta/posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block conntent %}

<!-- This is my template for PostDetailView  -->

<div class="container">
    <div class="card text-center" style="width: 30rem;">
        <img src="{{object.image.url}}" class="card-img-top" alt="Card image cap">
        <div class="card-body">

            <!-- POST -->
            <p class="card-text">{{ object.caption }}</p>
            <p>Author: {{ object.author }}</p>
            <p>Date of create: {{ object.date_of_publication }}</p>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="{% url 'posts:delete' post.pk %}" class="btn btn-danger">Delete</a>
                    <a href="{% url 'posts:update' post.pk %}" class="btn btn-primary">Update</a>
                </li>

                <!-- COMMENTS -->
                <h4>Comments for this photo:</h4>
                {% for comment in object.comments.all %}
                    <li class="list-group-item">
                        <p>Comment by:<strong>{{ comment.comment_author }}</strong></p>
                        <p><strong>Comment: </strong> {{ comment.body }}</p>
                    </li>
                {% empty %}
                    <li>
                        <p>No comments</p>
                    </li>     
                {% endfor %}
              </ul>

            <!-- FORM FOR COMMENTS -->
            {% if user.is_authenticated %}
                <form method="POST" name="PostDetailView">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_body">Add new comment</label>
                        <textarea class="form-control" name="body" id="id_body" cols="30" rows="5"></textarea>
                        <input type="submit" class="btn btn-primary" value="add comment" name="PostDetailView">
                    </div>
                </form>
            {% else %}
                <p>If you want to add a comment you have to be log in</p>
                <a href="{% url 'accounts:login' %}"><button class="btn btn-primary">Log In</button></a>
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}

mini_insta/posts/templates/posts/post_form.html
{% extends 'base.html' %}
{% block conntent %}

<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        <p>{{form.image}}</p>
        <label>caption</label>
        <p>{{form.caption}}</p>
    </div>
    <input type="submit" value="update">
</form>

{% endblock %}

mini_insta/posts/templates/posts/post_list.html
{% extends 'base.html' %}
{% block conntent %}


    
    {% for post in object_list %}
        <div class="container">
            <div class="card text-center" style="width: 30rem;">
                <img src="{{post.image.url}}" class="card-img-top" alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">{{ post.caption }}</p>
                    <p>Author: {{ post.author }}</p>
                    <p>Date of create: {{ post.date_of_publication }}</p>
                    <a href="{% url 'posts:detail' post.pk %}" class="btn btn-primary">Detail</a>
                    <a href="{% url 'posts:update' post.pk %}" class="btn btn-primary">Update</a>
        
                </div>
            </div>
        </div>
    <br>

    {% endfor %}

{% endblock %}