mini_insta/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('create/', views.create_group, name='group'),
    path('list/', views.GroupListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.GroupDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', views.GroupDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', views.GroupUpdateView.as_view(), name='update'),
]

mini_insta/mini_insta/urls.py
from django.contrib import admin
from django.urls import path, include
from my_site import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(), name="home"),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('groups/', include('groups.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mini_insta/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns= [
    path('create/', views.create_post, name='create_post'),
    path('list/', views.PostListView.as_view(), name='list'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', views.detail_view, name='detail'),


]

mini_insta/groups/models.py
from django.db import models
from posts.models import Post
from django.contrib.auth import get_user_model
from django.urls import reverse
# Create your models here.

User = get_user_model()

class Group(models.Model):
    admin_of_group = models.ForeignKey(User, on_delete=models.CASCADE)
    name_of_group = models.CharField(unique=True, max_length=256)
    description_of_group = models.TextField(blank=True, default="This Group has not their destription yet")
    members = models.ManyToManyField(User, related_name='members', related_query_name='member', blank=True)
    posts_in_group = models.ManyToManyField(Post, blank=True)

    def get_absolute_url(self):
        return reverse('groups:detail', kwargs={'pk':self.pk})        

    def __str__(self):
        return self.name_of_group

mini_insta/groups/forms.py
from django.forms import ModelForm
from .models import Group

#GROUPS FORMS.PY

class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = [ 'name_of_group', 'description_of_group']

mini_insta/groups/views.py
from django.shortcuts import render, redirect
from .forms import GroupForm
from .models import Group
from django.contrib.auth.decorators import login_required
from django.views.generic import (ListView, DetailView, DeleteView, UpdateView)
from django.urls import reverse_lazy, reverse

# Create your views here.

@login_required
def create_group(request):
    if request.POST:
        if 'create_group' in request.POST:
            name_of_group = request.POST.get('name_of_group')
            description_of_group = request.POST.get('description_of_group')
            admin_of_group = request.user
            

            group_object = Group.objects.create(name_of_group = name_of_group, description_of_group = description_of_group, admin_of_group = admin_of_group)
            group_object.members.add(admin_of_group)
            return redirect('home')

    context = {

    }
    return render(request, 'groups/create_group.html', context)


class GroupListView(ListView):
    model = Group

class GroupDetailView(DetailView):
    model = Group

class GroupDeleteView(DeleteView):
    model = Group
    template_name = 'groups/confirm_delete.html'

    success_url = reverse_lazy('groups:list')

    def get_queryset(self):
        user = self.request.user
        return Group.objects.filter(admin_of_group=user)

class GroupUpdateView(UpdateView):
    model = Group
    fields = ['name_of_group', 'description_of_group']
    success_url = reverse_lazy('groups:list')

mini_insta/groups/templates/groups/confirm_delete.html
{% extends 'base.html' %}
{% block conntent %}
<h4>Are you sure you wont delete this group?</h4>

<div class="card text-center" style="width: 18rem;">
    <form method="POST">
        {% csrf_token %}
        <h2>{{ object.name_of_group }}</h2>

        <input type="submit" class="btn btn-danger" value="delete">
        </div>

    </form>
</div>



{% endblock %}

mini_insta/groups/templates/groups/create_group.html
{% extends 'base.html' %}
{% block conntent %}
<div cllas="container">
    <h1>Create group:</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="text" id='id_name_of_group' required name="name_of_group">
        <textarea cllas="" name="description_of_group" id="id_description_of_group" cols="30" rows="10"></textarea>
        <input type="submit" cllas="" value="Create" name="create_group">
    </form>
</div>


{% endblock %}

mini_insta/groups/templates/groups/group_detail.html
{% extends 'base.html' %}
{% block conntent %}


<div class="card text-center" style="width: 30rem;">
    <div class="card-body">
        <h2>{{ object.name_of_group }}</h2>
        <p>{{ object.description_of_group }}</p>
        <p>{{ object.members }}</p>
        <p>{{ object.posts_in_group }}</p>
        <a href="{% url 'groups:delete' group.pk %}" class="btn btn-danger">Delete</a>
        <a href="{% url 'groups:update' group.pk %}" class="btn btn-primary">Update</a>
</div>

    
</div>

{% endblock %}

mini_insta/groups/templates/groups/group_form.html
{% extends 'base.html' %}
{% block conntent %}

<form method="POST" class="form-group">
    {% csrf_token %}
    <div class="form-group">
        <label>Name of group</label>
        <p>{{form.name_of_group}}</p>
        <label>description</label>
        <p>{{form.description_of_group}}</p>
    </div>
    
    

    <input type="submit" name="update">
</form>

<!-- <form method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_name_of_group">Name of group</label>
        {{form.name_of_group}}
    </div>
    <div class="form-group">
        <label for="id_description_of_group">description</label>
        <textarea class="form-control" id="id_description_of_group" rows="3"></textarea>
    </div>

    <input type="submit" class="btn btn-primary" value="update" name="create_group">
</form> -->
{% endblock %}

mini_insta/groups/templates/groups/group_list.html
{% extends 'base.html' %}
{% block conntent %}

{% for group in object_list %}
    <div class="container card">
        <h2>{{ group.name_of_group }}</h2>
        <p>{{ group.description_of_group }}</p>
        <p>{{ group.members }}</p>
        <p>{{ group.posts_in_group }}</p>
        <a href="{% url 'groups:detail' group.pk %}">Detail</a>
    </div>
{% endfor%}

{% endblock %}