mini_insta/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from . import views
from django.conf import settings


app_name = 'accounts'

urlpatterns = [
    path('login1/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login_view, name="login"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name="profile"),
    path('update/<int:pk>/', views.ProfileUpdateView.as_view(), name='update'),
    path('email_change/', views.emial_change, name='email_change'),
    path('new_emial_activate/<uidb64>/<token>/', views.new_email_activate, name='new_email_activate'),


    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html", 
        email_template_name='accounts/password_reset_email.html',
        success_url='/accounts/reset_password_sent/'),
        name='reset_password'),

    path('reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_done.html",
        success_url='/accounts/reset_password_complete/'),
        name='password_reset_confirm'),

    path('reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_succes"),
        name='password_reset_complete'),

] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mini_insta/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('create/', views.create_group, name='group'),
    path('list/', views.GroupListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.GroupDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', views.GroupDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', views.GroupUpdateView.as_view(), name='update'),
]

mini_insta/mini_insta/urls.py
from django.contrib import admin
from django.urls import path, include
from my_site import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(), name="home"),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('groups/', include('groups.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mini_insta/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns= [
    path('create/', views.create_post, name='create_post'),
    path('list/', views.PostListView.as_view(), name='list'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', views.detail_view, name='detail'),


]

mini_insta/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mini Insta</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #42647a;">
        <a class="navbar-brand" href="#">
          <img src="/home/dominika/folders/projects/website/mini_insta/media/icon.png" alt="">
        </a>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'posts:list' %}">Posts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'groups:list' %}">Groups</a>
              </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            {% if user.is_authenticated %}
              <a href="{% url 'accounts:logout' %}" class="btn btn-outline-dark">Log Out</a>
            {% else %}
              <a href="{% url 'accounts:login' %}" class="btn btn-outline-dark">Log In</a>
              <a href="{% url 'accounts:signup' %}" class="btn btn-outline-dark">Sign Up</a>
            {% endif %}
            </form>
        </div>
      </nav>


    <div class="container">
      <img src="/home/dominika/folders/projects/website/mini_insta/media/c5ed1c6175.0.jpeg" alt="" sizes="" srcset=""> 
    {% block conntent %}
    {% endblock %}
    </div>
</body>
</html>

mini_insta/templates/home.html
{% extends 'base.html' %}
{% block conntent %}
<h1>Welcome!</h1>
{% endblock %}