mini_insta/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from . import views
from django.conf import settings


app_name = 'accounts'

urlpatterns = [
    path('login1/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login_view, name="login"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name="profile"),
    path('update/<int:pk>/', views.ProfileUpdateView.as_view(), name='update'),
    path('email_change/', views.emial_change, name='email_change'),
    path('new_emial_activate/<uidb64>/<token>/', views.new_email_activate, name='new_email_activate'),


    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html", 
        email_template_name='accounts/password_reset_email.html',
        success_url='/accounts/reset_password_sent/'),
        name='reset_password'),

    path('reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_done.html",
        success_url='/accounts/reset_password_complete/'),
        name='password_reset_confirm'),

    path('reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_succes"),
        name='password_reset_complete'),

] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mini_insta/mini_insta/urls.py
from django.contrib import admin
from django.urls import path, include
from my_site import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(), name="home"),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('groups/', include('groups.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mini_insta/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns= [
    path('create/', views.create_post, name='create_post'),
    path('list/', views.PostListView.as_view(), name='list'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', views.detail_view, name='detail'),


]

mini_insta/accounts/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth.models import User
from PIL import Image
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    image = models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')

    def __str__(self):
        return self.user.username 

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
           output_size = (300, 300)
           img.thumbnail(output_size)
           img.save(self.image.path)

class EmailChangeAuth(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='email_change')
    new_email = models.EmailField(max_length=125)

    def __str__(self):
        return f'User {self.user.username} email is {self.new_email}'

    def save_changes(self, *args, **kwargs):
        user = User.objects.get(username=self.user)
        user.email = self.new_email
    

        

mini_insta/accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
# ACCOUNTS FORMS.PY

class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')



# class UserCreationForm(forms.ModelForm):
#     password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
#     password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)
   
#     class Meta:
#         model = get_user_model()
#         fields = ("username", "email", "password1", "password2")
 
#     def clean_password2(self):
#         password1 = self.cleaned_data.get('password1')
#         password2 = self.cleaned_data.get('password2')

#     def save(self, commit=True):
#         user = super(UserCreationForm, self).save(commit=False)
#         user.set_password(self.cleaned_data["password1"])
#         if commit:
#             user.save()
#         return user

class AuthenticationForm(forms.ModelForm):
    
    class Meta:
        model = get_user_model()
        fields = ('username', 'password')

mini_insta/accounts/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.shortcuts import HttpResponse

from . import forms

from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from .forms import SignupForm



from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.contrib.auth.decorators import  login_required

from django.core.mail import EmailMessage
from .tokens import account_activation_token, email_activation_token
from django.core.mail import send_mail

from django.contrib.auth.models import User
from .models import EmailChangeAuth

from django.contrib import messages

@login_required
def emial_change(request):
    User = get_user_model()
    if 'change_email' in request.POST:
        new_email = request.POST.get('new_email')
        user = request.user
        EmailChangeAuth.objects.create(user=user, new_email=new_email)

        mail_subject = 'Confirm new email'
        current_site = get_current_site(request)
        message = render_to_string('accounts/email_template_change_email.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': email_activation_token.make_token(user)
        })
        send_mail(mail_subject, message, 'dev.django.git@gmail.com', [new_email])
        return HttpResponse('Check your email and confirm your new email address')
    
    context = {

    }

    return render(request, 'accounts/change_email.html', context)


def new_email_activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and email_activation_token.check_token(user, token):
        email_change = EmailChangeAuth.objects.get(user=user)
        email_change.save_changes()
        email_change.delete()
        return HttpResponse('Thank you for your email confirmation. Your email is change')
    else:
        return HttpResponse('Activation link is invalid!')
    

def signup(request):
    User = get_user_model()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('accounts/email_template.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            send_mail(mail_subject, message, 'dev.djang.git@gmail.com', [to_email])
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignupForm()

    return render(request, 'accounts/regform.html', {'form': form})


        

def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')



from .forms import AuthenticationForm
from django.contrib.auth import authenticate, login

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        
        else:
            messages.error(request, 'user name or password is incorrect')

    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form':form})



from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from .models import Profile
from django.urls import reverse_lazy

class ProfileView(DetailView):

    model = Profile
    template_name = 'accounts/profile_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class ProfileUpdateView(UpdateView):

    model = User
    template_name = 'accounts/update_profile.html'

    fields = ['username', 'email']

    success_message = "Updated Successfully" 
    success_url = reverse_lazy('accounts:profile')

mini_insta/accounts/templates/accounts/change_email.html
{% extends 'base.html' %}
{% block conntent %}

<form method="POST">
    {% csrf_token %}
    <input type="email" name="new_email">
    <input type="submit" value="change email" name="change_email">
</form>

{% endblock %}

mini_insta/accounts/templates/accounts/edit_email.html
{% extends 'base.html' %}
{% block conntent %}

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="change" name="change_email">
</form>

{% endblock %}

mini_insta/accounts/templates/accounts/email_template.html
{% autoescape off %}
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

mini_insta/accounts/templates/accounts/email_template_change_email.html
{% autoescape off %}
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'accounts:new_email_activate' uidb64=uid token=token %}
{% endautoescape %}

mini_insta/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block conntent %}
<div class="container">
    <h2>Log in </h2>
    <form method="POST" name="login_view">   
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">User name</label>
            <input type="text" class="form-control" id="id_username" name="username">
          </div>
          <div class="form-group">
            <label for="id_password">Password</label>
            <input type="password" class="form-control" id="id_password" name="password">
        </div>
        {% for message in messages %}
        {{ message }}
        {% endfor %}
        <br/>
        <input type="submit" value="Log in" name="login_view">
    </form>
    <br>
    <h5>If you don't have account <a href="{% url 'accounts:signup' %}">Sign up</a></h5>
    
</div>


{% endblock %}

mini_insta/accounts/templates/accounts/profile_view.html
{% extends 'base.html' %}
{% block conntent %}

<div class="container jumbotron">
    {{ user.username }}
    {{ user.email }}
    <img src="{{ object.image.url }}" alt="">
</div>

{% endblock %}

mini_insta/accounts/templates/accounts/regform.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <!-- {% for field in form %}
        <label >{{ field.label_tag }}</label>
        {{ field }}
    {% endfor %} -->
    <input type="submit" value="register">
</form>

mini_insta/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block conntent %}

<form method="POST" name="signup">
    {% csrf_token %}


    <div class="form-group">
        <label for="id_username">Username</label>
        <input type="text" class="form-control" id="id_username" aria-describedby="emailHelp" name="username">
        <div class='error'>{{form.errors.username}}</div>
        <small id="id_username" class="form-text text-muted">Username have to be unique</small>
    </div>
    <div class="form-group">
        <label for="id_email">Email address</label>
        <input type="email" class="form-control" id="id_email" aria-describedby="emailHelp" name="email">
        <div class='error'>{{form.errors.email}}</div>
        <small id="id_email" class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>
    <div class="form-group">
        <label for="id_password">Password</label>
        <input type="password" class="form-control" id="id_password" name="password1">
        <div class='error'>{{form.errors.password1}}</div>
    </div>
    <div class="form-group">
        <label for="id_password_2">Repeat password</label>
        <input type="password" class="form-control" id="id_password_2" name="password2">
        <div class='error'>{{form.errors.password2}}</div>
    </div>
    <input type="submit" value="Sign up" name="signup">
</form>

{% endblock %}

mini_insta/accounts/templates/accounts/update_profile.html
{% extends 'base.html' %}
{% block conntent %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="change">
</form>

{% endblock %}